# Generated by Django 4.2 on 2023-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='is_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
