# Generated by Django 4.2 on 2023-04-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todomodel_is_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'ordering': ['-created']},
        ),
    ]
